version: '3.4'

services:
  
  web:
    environment:
      - CLAPBOT_ENVIRON=dev
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=clapbot.local
  
  flask.debug:
    environment:
      - FLASK_DEBUG=True
  
  celery.flower:
    ports:
      - "5555:5555"