version: '3.4'

x-service-base: &base
  restart: unless-stopped
  build: &base_build
    context: .
    dockerfile: Dockerfile
  environment: &base_environment
    - CLAPBOT_SETTINGS
    - CLAPBOT_ENVIRON
  networks:
    - back

networks:
  reverse-proxy:
    external:
      name: reverse-proxy
  back:
    driver: bridge

services:
  
  # Postgres
  db:
    image: postgres
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clapbot
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./data/pgdata/:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - back
  
  # Redis
  redis:
    image: redis:2.8.19
    hostname: redis
    networks:
      - back
  
  # Flask base
  flask.debug:
    <<: *base
    entrypoint: ./scripts/flask.sh
    command: run --host='0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
      - celery.worker
    links:
      - db
      - redis
  
  web:
    <<: *base
    command: ./scripts/nginx-start.sh
    environment:
      - CLAPBOT_ENVIRON
      - VIRTUAL_PORT
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
    depends_on:
      - db
      - celery.worker
      - celery.beat
    links:
      - db
      - redis
    networks:
      - reverse-proxy
      - back
  
  # Celery worker base
  celery.worker:
    <<: *base
    command: ./scripts/celery-worker.sh
    links:
      - db
      - redis
    depends_on:
      - redis
  
  celery.beat:
    <<: *base
    command: ./scripts/celery-beat.sh
    links:
      - db
      - redis
    depends_on:
      - redis
  
  # Celery flower
  celery.flower:
    <<: *base
    command: ./scripts/celery-flower.sh
    ports:
      - "5555:5555"
    links:
      - db
      - redis
    depends_on:
      - redis