FROM python:3.6

RUN apt-get update -y
RUN pip install pipenv

ENV FLASK_APP=clapbot

RUN mkdir -p /app
WORKDIR /app


# Copy the entrypoint that will generate Nginx additional configs
COPY services/ /app/services/
RUN chmod -R +x /app/services


COPY Pipfile Pipfile
COPY Pipfile.lock Pipfile.lock

# -- Install dependencies:
RUN pipenv install --deploy --system

COPY . /app

RUN pip install tox

ENTRYPOINT ["services/entrypoint-test.sh"]
CMD ["tox"]
