version: '3.4'

services:

  db:
    environment:
      - POSTGRES_DB=clapbotdev

  db-psql:
    command: ['psql', '--host=db', '--user=postgres', '--dbname=clapbotdev']

  web:
    volumes:
      - .:/app
    environment:
      - CLAPBOT_ENVIRON=dev
      - VIRTUAL_HOST=clapbot.local

  flask.debug:
    volumes:
      - .:/app
    environment:
      - CLAPBOT_ENVIRON=dev
      - FLASK_DEBUG=True
      - VIRTUAL_HOST=dev.clapbot.local
      - VIRTUAL_PORT=5000
    networks:
      - backend
      - reverse-proxy

  celery.flower:
    volumes:
      - .:/app
    environment:
      - CLAPBOT_ENVIRON=dev
      - VIRTUAL_HOST=flower.clapbot.local
      - VIRTUAL_PORT=5555

  celery.worker:
    environment:
      - CLAPBOT_ENVIRON=dev
    volumes:
      - .:/app

  celery.beat:
    environment:
      - CLAPBOT_ENVIRON=dev
    volumes:
      - .:/app