"""site_enabled

Revision ID: 02802a6f2380
Revises: 287659572c19
Create Date: 2018-06-04 02:50:35.586354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02802a6f2380'
down_revision = '287659572c19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clsite', sa.Column('enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clsite', 'enabled')
    # ### end Alembic commands ###
