"""search_enabled_column

Revision ID: 196c6fba2562
Revises: e26adfa8522c
Create Date: 2018-06-05 03:46:54.744772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '196c6fba2562'
down_revision = 'e26adfa8522c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('housingsearch', sa.Column('enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('housingsearch', 'enabled')
    # ### end Alembic commands ###
