"""clinfo

Revision ID: 287659572c19
Revises: f4cf74cc1ccf
Create Date: 2018-06-04 01:56:38.807700

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '287659572c19'
down_revision = 'f4cf74cc1ccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clcategory', sa.Column(
        'id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=True),
                    sa.PrimaryKeyConstraint('id'))
    op.create_table('clsite', sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=True),
                    sa.PrimaryKeyConstraint('id'))
    op.create_table('clarea', sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('site_id', sa.Integer(), nullable=True),
                    sa.Column('name', sa.String(length=255), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['site_id'],
                        ['clsite.id'],
                    ), sa.PrimaryKeyConstraint('id'))

    op.drop_column('housingsearch', 'cl_site')
    op.drop_column('housingsearch', 'cl_area')

    op.add_column('housingsearch',
                  sa.Column('cl_site', sa.Integer(), nullable=True))
    op.add_column('housingsearch',
                  sa.Column('cl_area', sa.Integer(), nullable=True))

    op.add_column('housingsearch',
                  sa.Column('cl_category', sa.Integer(), nullable=True))

    op.create_foreign_key(None, 'housingsearch', 'clcategory', ['cl_category'],
                          ['id'])
    op.create_foreign_key(None, 'housingsearch', 'clarea', ['cl_area'], ['id'])
    op.create_foreign_key(None, 'housingsearch', 'clsite', ['cl_site'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'housingsearch', type_='foreignkey')
    op.drop_constraint(None, 'housingsearch', type_='foreignkey')
    op.drop_constraint(None, 'housingsearch', type_='foreignkey')
    op.drop_column('housingsearch', 'cl_category')
    op.drop_column('housingsearch', 'cl_site')
    op.drop_column('housingsearch', 'cl_area')

    op.add_column('housingsearch',
                  sa.Column('cl_site', sa.String(length=255), nullable=True))
    op.add_column('housingsearch',
                  sa.Column('cl_area', sa.String(length=255), nullable=True))

    op.drop_table('clarea')
    op.drop_table('clsite')
    op.drop_table('clcategory')
    # ### end Alembic commands ###
