"""empty message

Revision ID: 28bd2c824e14
Revises:
Create Date: 2018-06-03 06:10:40.784072

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '28bd2c824e14'
down_revision = '6c96742d9817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'status',
            sa.Enum('registered', 'active', 'deactivated', name='userstatus'),
            nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
