"""scraped_at

Revision ID: 6665b177a29e
Revises: aedcad43dc60
Create Date: 2018-06-06 05:07:52.909372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6665b177a29e'
down_revision = 'aedcad43dc60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraperecord', sa.Column('scraped_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraperecord', 'scraped_at')
    # ### end Alembic commands ###
