"""Add default filters for housing serach.

Revision ID: 854a93e08b80
Revises: 02802a6f2380
Create Date: 2018-06-04 03:13:19.128609

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '854a93e08b80'
down_revision = '02802a6f2380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('housingsearch', sa.Column('price_max', sa.Integer(), nullable=True))
    op.add_column('housingsearch', sa.Column('price_min', sa.Integer(), nullable=True))
    op.add_column('housingsearch', sa.Column('require_images', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('housingsearch', 'require_images')
    op.drop_column('housingsearch', 'price_min')
    op.drop_column('housingsearch', 'price_max')
    # ### end Alembic commands ###
