"""scrape_record

Revision ID: aedcad43dc60
Revises: e7bd119c3efb
Create Date: 2018-06-05 15:57:54.323236

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision = 'aedcad43dc60'
down_revision = 'e7bd119c3efb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('scraperecord', sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('cl_area', sa.Integer(), nullable=True),
                    sa.Column('cl_category', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('status', sa.Enum('pending', 'started', 'finished', name='scrapestatus'), nullable=True),
                    sa.Column('result', sa.String(length=255), nullable=True),
                    sa.Column('records', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['cl_area'],
                        ['clarea.id'],
                    ), sa.ForeignKeyConstraint(
                        ['cl_category'],
                        ['clcategory.id'],
                    ), sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scraperecord')
    if op.get_bind().engine.name == 'postgresql':
        op.execute("DROP TYPE scrapestatus;")
    # ### end Alembic commands ###
