"""category_description

Revision ID: e26adfa8522c
Revises: 854a93e08b80
Create Date: 2018-06-04 03:18:52.793766

"""
from alembic import op
import sqlalchemy as sa
from pathlib import Path
from pkg_resources import resource_filename

# revision identifiers, used by Alembic.
revision = 'e26adfa8522c'
down_revision = '854a93e08b80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clcategory', sa.Column('description', sa.String(length=255), nullable=True))
    script = Path(resource_filename('clapbot', 'data/categories.sql')).read_text()
    op.execute(script + ";")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE clcategory")
    op.drop_column('clcategory', 'description')
    # ### end Alembic commands ###
