#!/bin/bash
if [ -n "$CLAPBOT_ENVIRON" -a -d "config/$CLAPBOT_ENVIRON/" ]; then
  OVERRIDES="config/$CLAPBOT_ENVIRON/docker-compose.yml"
fi
OVERRIDES="${OVERRIDES:-docker-compose.dev.yml}"

docker-compose -f docker-compose.yml -f "$OVERRIDES" $@